2021-05-17 00:03:52,182 - INFO: Started server process [12244]
2021-05-17 00:03:52,182 - INFO: Waiting for application startup.
2021-05-17 00:03:52,183 - INFO: Application startup complete.
2021-05-17 00:03:54,652 - ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\fastapi\routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "c:\users\lucas\appdata\local\pypoetry\cache\virtualenvs\app-r1mvpay6-py3.8\lib\site-packages\fastapi\routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 58, in get_cats
    logger.info('Querying all cats that have {} as coat length.'.format(coat_length))
NameError: name 'logger' is not defined
2021-05-17 00:04:07,722 - INFO: Started server process [16832]
2021-05-17 00:04:07,723 - INFO: Waiting for application startup.
2021-05-17 00:04:07,723 - INFO: Application startup complete.
2021-05-17 00:04:33,309 - INFO: Started server process [17076]
2021-05-17 00:04:33,309 - INFO: Waiting for application startup.
2021-05-17 00:04:33,309 - INFO: Application startup complete.
2021-05-17 00:04:33,402 - INFO: Querying all cats that have 4 as coat length.
